blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/gtkacz/whenever-django/discussions
    about: Ask questions or start a discussion about whenever-django usage
